[metrics]
weekly = ["organic_search_count", "tagged_search_count", "tagged_follow_on_search_count",
"searchalias_counts", "searchalias_amazon_counts", "searchoneoff_amazon_counts", "searchmode_counts", "searchmode_amazon_counts", "searchmode_searchoneoff_amazon_counts", "search_engagement"]

[metrics.searchalias_counts]
select_expression = "SUM(CASE WHEN source = 'alias' then sap else 0 end)"
data_source = "search_clients_daily"
[metrics.searchalias_counts.bootstrap_mean]
[metrics.searchalias_counts.deciles]

[metrics.searchalias_amazon_counts]
select_expression = "SUM(CASE WHEN source = 'alias' and engine like 'amazon%' then sap else 0 end)"
data_source = "search_clients_daily"
[metrics.searchalias_amazon_counts.bootstrap_mean]
[metrics.searchalias_amazon_counts.deciles]

[metrics.searchoneoff_amazon_counts]
select_expression = "SUM(CASE WHEN source = 'urlbar' and engine like 'amazon%' then sap else 0 end)"
data_source = "search_clients_daily"
[metrics.searchoneoff_amazon_counts.bootstrap_mean]
[metrics.searchoneoff_amazon_counts.deciles]

[metrics.searchmode_counts]
select_expression = "SUM(CASE WHEN source = 'urlbar-searchmode' then sap else 0 end)"
data_source = "search_clients_daily"
[metrics.searchmode_counts.bootstrap_mean]
[metrics.searchmode_counts.deciles]

[metrics.searchmode_amazon_counts]
select_expression = "SUM(CASE WHEN source = 'urlbar-searchmode' and engine like 'amazon%' then sap else 0 end)"
data_source = "search_clients_daily"
[metrics.searchmode_amazon_counts.bootstrap_mean]
[metrics.searchmode_amazon_counts.deciles]

[metrics.searchmode_searchoneoff_amazon_counts]
select_expression = "SUM(CASE WHEN source = 'urlbar' and engine like 'amazon%' then sap else 0 end)"
data_source = "search_clients_daily"
[metrics.searchmode_searchoneoff_amazon_counts.bootstrap_mean]
[metrics.searchmode_searchoneoff_amazon_counts.deciles]

[metrics.search_engagement]
select_expression = "(SUM(tagged_sap) + SUM(tagged_follow_on))*100.0 / (SUM(organic) + SUM(tagged_sap) + SUM(tagged_follow_on))"
data_source = "search_clients_daily"
[metrics.search_engagement.bootstrap_mean]
[metrics.search_engagement.deciles]
