version: 2.1

jobs:
  validate:
    docker:
    - image: gcr.io/moz-fx-data-experiments/pensieve:latest
    steps:
    - checkout
    - run:
        name: Validate config files
        command: echo "TODO validate configs" # todo
  rerun:
    docker:
    - image: google/cloud-sdk
    steps:
    - checkout
    - &skip_forked_pr
      run:
        name: Early return if this build is from a forked PR
        command: |
          if [ -n "$CIRCLE_PR_NUMBER" ]; then
            echo "Do not re-run analysis on forked PRs, so marking this step successful"
            circleci step halt
          fi
    - run:
        name: Authorize gcloud CLI
        command: |
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp.json"
          echo "$GCLOUD_SERVICE_KEY" > "$GOOGLE_APPLICATION_CREDENTIALS"
          gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
    - run:
        name: Trigger pensieve re-run
        command: |
          gcloud config set project $GCLOUD_PROJECT
          gcloud functions call trigger-pensieve
  build-and-deploy:
    jobs:
      - validate
      - rerun
